export const courses = [
  {
    subject: 'Biology Grade 12',
    category: 'HighSchool',
    price: 100,
    createdAt: '20-03-2024',
  },
  {
    subject: 'Psychology',
    category: 'Freshman',
    price: 120,
    createdAt: '12-01-2024',
  },
  {
    subject: 'Flutter complete course',
    category: 'Development',
    price: 150,
    createdAt: '01-05-2024',
  },
  {
    subject: 'Mathematics Advanced',
    category: 'HighSchool',
    price: 90,
    createdAt: '15-02-2024',
  },
  {
    subject: 'Introduction to Computer Science',
    category: 'Freshman',
    price: 110,
    createdAt: '05-04-2024',
  },
  {
    subject: 'Web Design Fundamentals',
    category: 'Development',
    price: 80,
    createdAt: '22-03-2024',
  },
  {
    subject: 'Chemistry Basics',
    category: 'HighSchool',
    price: 95,
    createdAt: '18-01-2024',
  },
  {
    subject: 'Art History',
    category: 'Freshman',
    price: 130,
    createdAt: '10-05-2024',
  },
  {
    subject: 'React.js Crash Course',
    category: 'Development',
    price: 160,
    createdAt: '03-06-2024',
  },
  {
    subject: 'Physics for Beginners',
    category: 'HighSchool',
    price: 85,
    createdAt: '28-02-2024',
  },
  {
    subject: 'Introduction to Psychology',
    category: 'Freshman',
    price: 115,
    createdAt: '15-04-2024',
  },
  {
    subject: 'Node.js Basics',
    category: 'Development',
    price: 140,
    createdAt: '08-03-2024',
  },
  {
    subject: 'Environmental Science',
    category: 'HighSchool',
    price: 105,
    createdAt: '24-01-2024',
  },
  {
    subject: 'History of Literature',
    category: 'Freshman',
    price: 125,
    createdAt: '20-05-2024',
  },
  {
    subject: 'Python Programming Masterclass',
    category: 'Development',
    price: 170,
    createdAt: '12-06-2024',
  },
  {
    subject: 'Geography Exploration',
    category: 'HighSchool',
    price: 88,
    createdAt: '18-02-2024',
  },
  {
    subject: 'Sociology Perspectives',
    category: 'Freshman',
    price: 135,
    createdAt: '05-04-2024',
  },
  {
    subject: 'Angular Framework Fundamentals',
    category: 'Development',
    price: 155,
    createdAt: '30-03-2024',
  },
  {
    subject: 'Economics Basics',
    category: 'HighSchool',
    price: 98,
    createdAt: '22-01-2024',
  },
  {
    subject: 'Spanish Language Essentials',
    category: 'Freshman',
    price: 145,
    createdAt: '10-05-2024',
  },
  {
    subject: 'Advanced Chemistry Topics',
    category: 'HighSchool',
    price: 110,
    createdAt: '15-08-2024',
  },
  {
    subject: 'Introduction to Sociology',
    category: 'Freshman',
    price: 125,
    createdAt: '10-12-2024',
  },
  {
    subject: 'Machine Learning Fundamentals',
    category: 'Development',
    price: 180,
    createdAt: '02-08-2024',
  },
  {
    subject: 'Literary Analysis Workshop',
    category: 'HighSchool',
    price: 95,
    createdAt: '08-02-2024',
  },
  {
    subject: 'Artificial Intelligence Basics',
    category: 'Freshman',
    price: 140,
    createdAt: '18-04-2024',
  },
  {
    subject: 'Graphic Design Essentials',
    category: 'Development',
    price: 75,
    createdAt: '25-03-2024',
  },
  {
    subject: 'Earth Science Exploration',
    category: 'HighSchool',
    price: 105,
    createdAt: '20-12-2024',
  },
  {
    subject: 'Music Appreciation',
    category: 'Freshman',
    price: 130,
    createdAt: '12-11-2024',
  },
  {
    subject: 'Data Structures and Algorithms',
    category: 'Development',
    price: 160,
    createdAt: '05-09-2024',
  },
  {
    subject: 'Advanced Physics Concepts',
    category: 'HighSchool',
    price: 100,
    createdAt: '28-02-2024',
  },
  {
    subject: 'Introduction to Anthropology',
    category: 'Freshman',
    price: 120,
    createdAt: '15-04-2024',
  },
  {
    subject: 'Mobile App Development with React Native',
    category: 'Development',
    price: 150,
    createdAt: '08-03-2024',
  },
  {
    subject: 'Ecology and Environmental Sustainability',
    category: 'HighSchool',
    price: 95,
    createdAt: '24-01-2024',
  },
  {
    subject: 'Philosophy Basics',
    category: 'Freshman',
    price: 135,
    createdAt: '20-05-2024',
  },
  {
    subject: 'JavaScript Frameworks Overview',
    category: 'Development',
    price: 170,
    createdAt: '12-06-2024',
  },
  {
    subject: 'World History Chronicles',
    category: 'HighSchool',
    price: 90,
    createdAt: '18-02-2024',
  },
  {
    subject: 'Introduction to Political Science',
    category: 'Freshman',
    price: 145,
    createdAt: '05-04-2024',
  },
  {
    subject: 'Cybersecurity Essentials',
    category: 'Development',
    price: 155,
    createdAt: '30-03-2024',
  },
  {
    subject: 'Advanced Economics',
    category: 'HighSchool',
    price: 105,
    createdAt: '22-01-2024',
  },
  {
    subject: 'French Language Basics',
    category: 'Freshman',
    price: 140,
    createdAt: '10-07-2024',
  },
  {
    subject: 'Genetics and Molecular Biology',
    category: 'HighSchool',
    price: 115,
    createdAt: '10-03-2024',
  },
  {
    subject: 'Introduction to Political Philosophy',
    category: 'Freshman',
    price: 128,
    createdAt: '08-01-2024',
  },
  {
    subject: 'Full Stack Web Development',
    category: 'Development',
    price: 190,
    createdAt: '15-05-2024',
  },
  {
    subject: 'Creative Writing Workshop',
    category: 'HighSchool',
    price: 98,
    createdAt: '12-02-2024',
  },
  {
    subject: 'Human-Computer Interaction Fundamentals',
    category: 'Freshman',
    price: 145,
    createdAt: '22-04-2024',
  },
  {
    subject: 'UI/UX Design Principles',
    category: 'Development',
    price: 80,
    createdAt: '28-03-2024',
  },
  {
    subject: 'Astronomy and Astrophysics',
    category: 'HighSchool',
    price: 110,
    createdAt: '25-01-2024',
  },
  {
    subject: 'Introduction to Theater Arts',
    category: 'Freshman',
    price: 135,
    createdAt: '18-05-2024',
  },
  {
    subject: 'Blockchain Technology Basics',
    category: 'Development',
    price: 165,
    createdAt: '01-06-2024',
  },
  {
    subject: 'Environmental Chemistry',
    category: 'HighSchool',
    price: 105,
    createdAt: '20-02-2024',
  },
  {
    subject: 'Introduction to Linguistics',
    category: 'Freshman',
    price: 125,
    createdAt: '15-04-2024',
  },
  {
    subject: 'Django Web Framework',
    category: 'Development',
    price: 155,
    createdAt: '10-03-2024',
  },
  {
    subject: 'Oceanography Essentials',
    category: 'HighSchool',
    price: 100,
    createdAt: '24-01-2024',
  },
  {
    subject: 'World Religions Survey',
    category: 'Freshman',
    price: 138,
    createdAt: '20-05-2024',
  },
  {
    subject: 'Angular Frontend Development',
    category: 'Development',
    price: 175,
    createdAt: '12-06-2024',
  },
  {
    subject: 'European History Insights',
    category: 'HighSchool',
    price: 88,
    createdAt: '18-02-2024',
  },
  {
    subject: 'Introduction to Cultural Anthropology',
    category: 'Freshman',
    price: 142,
    createdAt: '05-04-2024',
  },
  {
    subject: 'Mobile Game Development with Unity',
    category: 'Development',
    price: 160,
    createdAt: '30-03-2024',
  },
  {
    subject: 'Advanced Macroeconomics',
    category: 'HighSchool',
    price: 102,
    createdAt: '22-01-2024',
  },
  {
    subject: 'Spanish Literature Appreciation',
    category: 'Freshman',
    price: 148,
    createdAt: '10-05-2024',
  },
];
